broker: tcp://127.0.0.1:1883
version: 4
username:
password:
topic:
  sub: test/request
  pub: test/response
ca:
  enable: false
  cafile: /etc/mosquitto/certs/ca.crt
  certfile: /etc/mosquitto/certs/client.crt
  keyfile: /etc/mosquitto/certs/client.key